package main

import "net/http"

func (s *service) routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /{$}", s.handleIndex)
	mux.HandleFunc("GET /healthz", s.handleHealth)
	mux.HandleFunc("GET /api/v1/supply", s.handleSupply)
	mux.HandleFunc("POST /api/v1/supply/start", s.handleSupplyStart)
	mux.HandleFunc("POST /api/v1/supply/stop", s.handleSupplyStop)
	mux.HandleFunc("POST /api/v1/supply/switch", s.handleSupplySwitch)
	mux.HandleFunc("POST /api/v1/supply/target", s.handleSupplyTarget)
	mux.HandleFunc("POST /api/v1/supply/sequence", s.handleSupplySequence)
	mux.HandleFunc("POST /api/v1/supply/dispatch", s.handleSupplyDispatch)
	mux.HandleFunc("GET /api/v1/pumps", s.handlePumps)
	mux.HandleFunc("POST /api/v1/pumps/mode", s.handlePumpMode)
	mux.HandleFunc("POST /api/v1/pumps/manual", s.handlePumpManual)
	mux.HandleFunc("GET /api/v1/hydrants", s.handleHydrants)
	mux.HandleFunc("POST /api/v1/hydrants/recover", s.handleHydrantRecover)
	mux.HandleFunc("GET /api/v1/hydrants/metrics", s.handleHydrantMetrics)
	mux.HandleFunc("GET /api/v1/hydrants/below-pressure", s.handleBelowPressure)
	mux.HandleFunc("POST /api/v1/hydrants/telemetry", s.handleTelemetry)
	mux.HandleFunc("POST /api/v1/hydrants/telemetry/batch", s.handleTelemetryBatch)
	mux.HandleFunc("GET /api/v1/alarms", s.handleAlarms)
	mux.HandleFunc("GET /api/v1/alarms/active", s.handleActiveAlarms)
	mux.HandleFunc("GET /api/v1/alarms/history", s.handleAlarmHistory)
	mux.HandleFunc("POST /api/v1/alarms/raise", s.handleAlarmRaise)
	mux.HandleFunc("POST /api/v1/alarms/escalate", s.handleAlarmEscalate)
	mux.HandleFunc("POST /api/v1/leak/detect", s.handleLeakDetect)
	mux.HandleFunc("POST /api/v1/leak/recover", s.handleLeakRecover)
	mux.HandleFunc("GET /api/v1/leak/status", s.handleLeakStatus)
	mux.HandleFunc("POST /api/v1/leak/interlock/reset", s.handleInterlockReset)
	mux.HandleFunc("POST /api/v1/leak/pressure-drop", s.handlePressureDrop)
	mux.HandleFunc("GET /api/v1/record", s.handleRecord)
	mux.HandleFunc("GET /api/v1/record/stats", s.handleRecordStats)
	mux.HandleFunc("GET /api/v1/record/export", s.handleRecordExport)
	mux.HandleFunc("POST /api/v1/record/rotate", s.handleRecordRotate)
	mux.HandleFunc("POST /api/v1/alarms/ack", s.handleAlarmAck)
	mux.HandleFunc("GET /api/v1/supply/metrics", s.handleSupplyMetrics)
	mux.HandleFunc("GET /api/v1/supply/switch", s.handleSwitchStatus)
	mux.HandleFunc("POST /api/v1/supply/switch/reset", s.handleSwitchReset)
	mux.HandleFunc("POST /api/v1/supply/switch/drain", s.handleDrainProgress)
	mux.HandleFunc("GET /api/v1/pumps/health", s.handlePumpHealth)
	mux.HandleFunc("POST /api/v1/pumps/failover", s.handlePumpFailover)
	mux.HandleFunc("POST /api/v1/pumps/schedule", s.handlePumpSchedule)
	return mux
}
